# yaml-language-server: $schema=<https://uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: aiConfiguration
name: 'AI Configuration '
icon: asterisk
parameters: []
categoryId: 096fd5ed-5e2a-4bfa-834b-fb805d1d1ce9
useTeamPermissions: true
slots:
  - id: interestRecommendations
    name: Interest Recommendations
    allowedComponents: []
    allowAllComponents: true
    inheritAllowedComponents: false
    patternsInAllowedComponents: false
  - id: cartRecommendations
    name: Cart Recommendations
    allowedComponents: []
    allowAllComponents: true
    inheritAllowedComponents: false
    patternsInAllowedComponents: false
  - id: cartPattern
    name: Cart Pattern
    allowedComponents: []
    allowAllComponents: true
    inheritAllowedComponents: false
    patternsInAllowedComponents: false
canBeComposition: true
created: '2025-04-02T18:34:39.190003+00:00'
updated: '2025-04-02T18:37:10.7649+00:00'
