id: product
name: Product
created: '2025-03-25T04:28:36.53123+00:00'
updated: '2025-04-01T11:18:59.039892+00:00'
slugSettings:
  required: 'no'
useTeamPermissions: true
fields:
  - id: title
    name: Title
    type: text
    typeConfig: null
  - id: name
    name: Product Name
    type: text
    typeConfig:
      required: true
  - id: shortDescription
    name: Short Description
    type: text
    typeConfig:
      multiline: true
      linesCount: 4
    localizable: true
  - id: body
    name: Body
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h2
          - h3
          - h4
          - unorderedList
          - orderedList
          - link
          - quote
          - variable
          - table
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
    localizable: true
  - id: primaryImage
    name: Primary Image
    type: asset
    typeConfig:
      max: 1
      min: 0
  - id: 53c66f1e-0962-41e2-bc01-8892c265ae34
    name: Taxonomy
    type: group
    typeConfig:
      collapsed: false
      childrenParams:
        - category
        - brand
        - variants
        - recommendations
  - id: category
    name: Category
    type: contentReference
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - productCategory
  - id: brand
    name: Brand
    type: contentReference
    typeConfig:
      allowedContentTypes:
        - brand
  - id: variants
    name: Variants
    type: $block
    typeConfig:
      min: 1
      allowedTypes:
        - $loop
        - variant
  - id: recommendations
    name: Recommendations
    type: contentReference
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - product
  - id: enrichments
    name: Enrichments
    type: $enr
    typeConfig: null
  - id: 78dea93f-5370-41dd-8d47-3544961c22c5
    name: Programatic Personalization
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - interest
  - id: interest
    name: Interest
    type: select
    typeConfig:
      options:
        - text: Coffee Makers
          value: coffee-makers
        - text: Coffee Beans
          value: beans
        - text: Everyone
          value: everyone
entryName: title
thumbnailField: primaryImage
description: ''
icon: shopping-cart
type: contentType
permissions: []
