id: product
name: Product
created: '2025-04-24T21:39:19.576736+00:00'
updated: '2025-05-09T08:24:20.178921+00:00'
slugSettings:
  required: 'no'
useTeamPermissions: true
fields:
  - id: title
    name: Title
    type: text
    typeConfig: null
  - id: name
    name: Product Name
    type: text
    typeConfig:
      required: true
  - id: keyFeatures
    name: Key Features
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
          - code
          - table
          - asset
          - variable
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
      elementsConfig:
        asset:
          allowedTypes:
            - image
    localizable: true
  - id: typicalApplications
    name: Typical Applications
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
          - code
          - table
          - asset
          - variable
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
      elementsConfig:
        asset:
          allowedTypes:
            - image
    localizable: true
  - id: overview
    name: Overview
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
          - code
          - table
          - asset
          - variable
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
      elementsConfig:
        asset:
          allowedTypes:
            - image
    localizable: true
  - id: parameters
    name: Parameters
    type: richText
    typeConfig:
      elements:
        builtIn:
          - table
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
      elementsConfig:
        asset:
          allowedTypes:
            - image
    localizable: true
  - id: primaryImage
    name: Primary Image
    type: asset
    typeConfig:
      max: 1
      min: 0
  - id: 53c66f1e-0962-41e2-bc01-8892c265ae34
    name: Taxonomy
    type: group
    typeConfig:
      collapsed: false
      childrenParams:
        - category
        - applications
        - enrichments
        - status
        - rohs
        - leadFree
        - halogenFree
        - relatedProducts
        - relatedResources
  - id: category
    name: Category
    type: contentReference
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - productCategory
  - id: applications
    name: Applications
    type: contentReference
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - productApplications
  - id: enrichments
    name: Enrichments
    type: $enr
    typeConfig: null
  - id: status
    name: Status
    type: select
    typeConfig:
      options:
        - text: Preview
          value: preview
        - text: Production
          value: production
        - text: Not Recommended For New Designs
          value: not-recommended-for-new-designs
        - text: Last Time Buy
          value: last-time-buy
  - id: rohs
    name: RoHS
    type: select
    typeConfig:
      options:
        - text: 'Yes'
          value: 'yes'
        - text: Unspecified
          value: unspecified
  - id: leadFree
    name: Lead Free
    type: select
    typeConfig:
      options:
        - text: 'Yes'
          value: 'Yes'
        - text: 'No'
          value: 'No'
        - text: Unspecified
          value: unspecified
  - id: halogenFree
    name: Halogen Free
    type: select
    typeConfig:
      options:
        - text: 'Yes'
          value: 'yes'
        - text: 'No'
          value: 'no'
        - text: Unspecified
          value: unspecified
  - id: relatedProducts
    name: Related Products
    type: contentReference
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - product
  - id: relatedResources
    name: Related Resources
    type: contentReference
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - resource
  - id: 83fd62af-d6b8-424a-9b10-35a8c4e62e46
    name: Documents
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - dataSheets
        - pcbLayoutFiles
        - sParameters
  - id: dataSheets
    name: Data Sheets
    type: asset
    typeConfig:
      allowedTypes:
        - other
  - id: pcbLayoutFiles
    name: PCB Layout Files
    type: asset
    typeConfig:
      allowedTypes:
        - other
  - id: sParameters
    name: S-Parameters
    type: asset
    typeConfig:
      allowedTypes:
        - other
entryName: title
thumbnailField: primaryImage
description: ''
icon: shopping-cart
type: contentType
permissions: []
previewConfigurations:
  - type: project-map
    id: 702b0e0b-3858-4b5d-99e4-bdb98097ca0f
    label: Product Detail Page
    dynamicInputs:
      locale: ${locale}
      product-slug: ${#jptr:/entry/_slug}
