# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: configuredBike
name: Configured Bike
icon: screen
parameters:
  - id: bikemodel
    name: BikeModel
    type: text
    typeConfig: null
    localizable: true
  - id: bikeimage
    name: BikeImage
    type: image
    typeConfig: null
    localizable: true
  - id: price
    name: Price
    type: number
    typeConfig: null
  - id: creationdate
    name: CreationDate
    type: date
    typeConfig: null
useTeamPermissions: true
slots: []
titleParameter: bikemodel
canBeComposition: false
created: '2025-06-12T07:28:26.739343+00:00'
updated: '2025-06-12T07:28:26.739343+00:00'
