# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productBullets
name: Product Bullets
icon: layout-list
parameters: []
categoryId: 90b009c6-707b-49b2-a1c0-c5916278855c
useTeamPermissions: true
slots: []
canBeComposition: false
created: '2025-06-12T07:28:33.797505+00:00'
updated: '2025-06-12T07:28:33.797505+00:00'
