# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productCardCarousel
name: Product Card Carousel
icon: arrows-h-alt
parameters: []
categoryId: 90b009c6-707b-49b2-a1c0-c5916278855c
useTeamPermissions: true
slots: []
canBeComposition: false
created: '2025-06-12T07:28:34.031132+00:00'
updated: '2025-06-12T07:28:34.031132+00:00'
