# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productVariantCard
name: Product variant card
icon: card
parameters:
  - id: image
    name: Image
    type: asset
    helpText: Manual override of image or if its not used with a pattern
    typeConfig:
      max: 1
      min: 0
      allowedTypes:
        - image
    allowConditionalValues: true
  - id: description
    name: Description
    type: text
    helpText: Manual override of description or if its not used with a pattern
    typeConfig: null
    localizable: true
  - id: price
    name: Price
    type: text
    helpText: Manual override of price or if its not used with a pattern
    typeConfig: null
    allowConditionalValues: true
  - id: title
    name: Title
    type: text
    helpText: Manual override of title or if its not used with a pattern
    typeConfig: null
    localizable: true
  - id: link
    name: Link
    type: link
    helpText: Manual override of link or if its not used with a pattern
    typeConfig:
      linkTypes:
        tel: false
        email: false
  - id: variant
    name: Variant
    type: json
    helpText: This is only used in a pattern or a loop
    typeConfig:
      required: false
  - id: categories
    name: Categories
    type: json
    helpText: This is only used in a pattern or a loop
    typeConfig: {}
  - id: slug
    name: Slug
    type: text
    helpText: This is only used in a pattern or a loop
    typeConfig: null
categoryId: 9ff00250-0200-45ec-82d3-4e3b346d7ee6
useTeamPermissions: true
slots: []
titleParameter: title
thumbnailParameter: image
canBeComposition: false
created: '2025-06-12T07:28:37.68883+00:00'
updated: '2025-06-12T07:28:37.68883+00:00'
