# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productCards
name: Product cards
icon: display-grid
parameters:
  - id: products
    name: Products
    type: commercetoolsProductList
    typeConfig:
      allowedProductCategories: {}
  - id: title
    name: Title
    type: text
    typeConfig: null
  - id: shortDescription
    name: Short description
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
  - id: longDescription
    name: Long description
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
categoryId: 90b009c6-707b-49b2-a1c0-c5916278855c
useTeamPermissions: true
slots: []
titleParameter: title
canBeComposition: false
created: '2025-06-12T07:28:34.269777+00:00'
updated: '2025-06-12T07:28:34.269777+00:00'
