# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productUsp
name: Product Usp
icon: dollar
parameters:
  - id: usptitle1
    name: UspTitle1
    type: text
    typeConfig:
      required: false
    localizable: true
  - id: uspicon1
    name: UspIcon1
    type: select
    typeConfig:
      options:
        - text: shipping
          value: shipping
        - text: warranty
          value: warranty
        - text: exchange
          value: exchange
    localizable: true
  - id: uspdescription1
    name: UspDescription1
    type: text
    typeConfig: null
    localizable: true
  - id: usptitle2
    name: UspTitle2
    type: text
    typeConfig: null
    localizable: true
  - id: uspicon2
    name: UspIcon2
    type: select
    typeConfig:
      options:
        - text: shipping
          value: shipping
        - text: warranty
          value: warranty
        - text: exchange
          value: exchange
    localizable: true
  - id: uspdescription2
    name: UspDescription2
    type: text
    typeConfig: null
    localizable: true
  - id: usptitle3
    name: UspTitle3
    type: text
    typeConfig: null
    localizable: true
  - id: uspdescription3
    name: UspDescription3
    type: text
    typeConfig: null
    localizable: true
  - id: uspicon3
    name: UspIcon3
    type: select
    typeConfig:
      options:
        - text: shipping
          value: shipping
        - text: warranty
          value: warranty
        - text: exchange
          value: exchange
    localizable: true
  - id: usptitle
    name: UspTitle
    type: text
    typeConfig: null
    localizable: true
categoryId: 90b009c6-707b-49b2-a1c0-c5916278855c
useTeamPermissions: true
slots: []
titleParameter: usptitle
canBeComposition: false
created: '2025-06-12T07:28:37.454211+00:00'
updated: '2025-06-12T07:28:37.454211+00:00'
