# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productLinkCard
name: Product link  card
icon: card
parameters:
  - id: key
    name: Key
    type: text
    typeConfig: null
  - id: title
    name: Title
    type: text
    typeConfig: null
    localizable: true
  - id: description
    name: Description
    type: text
    helpText: 'Price or description. Use #{price  CENTAMOUNT} for price formatting'
    typeConfig: null
    localizable: true
  - id: image
    name: Image
    type: asset
    typeConfig:
      max: 1
      min: 0
      allowedTypes:
        - image
  - id: badge
    name: Badge
    type: text
    typeConfig: null
    localizable: true
    allowConditionalValues: true
  - id: link
    name: Link
    type: link
    typeConfig:
      linkTypes:
        tel: false
        email: false
    localizable: true
    notLocalizedByDefault: true
categoryId: 9ff00250-0200-45ec-82d3-4e3b346d7ee6
useTeamPermissions: true
slots: []
titleParameter: title
thumbnailParameter: image
canBeComposition: false
created: '2025-06-12T07:28:35.811741+00:00'
updated: '2025-06-12T07:28:35.811741+00:00'
