# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productlistordetailspage
name: Product List or Details Page
icon: screen
parameters: []
useTeamPermissions: true
slots:
  - id: content
    name: content
    allowedComponents:
      - productlistpage
      - productdetailspage
    allowAllComponents: false
    inheritAllowedComponents: false
    patternsInAllowedComponents: false
canBeComposition: true
created: '2025-06-12T07:28:36.2557+00:00'
updated: '2025-06-12T07:28:36.2557+00:00'
