import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/types/cskTypes.ts',
    'src/tailwindcss-conf.ts',
    'src/utils/styling.ts',
    'src/utils/routing.ts',
    'src/utils/assets.ts',
    'src/utils/createEmptyPlaceholderResolver.tsx',
    'src/utils/createComponentResolver.ts',
    'src/utils/getSlotComponents.ts',
    'src/utils/withSlotsDataValue.tsx',
    'src/utils/withFlattenParameters.tsx',
    'src/utils/sitemap.ts',
    'src/components/providers/server.ts',
    'src/components/ui/index.ts',
    'src/components/canvas/serverOnly.ts',
    'src/components/canvas/clientCompatible.ts',
    'src/components/canvas/index.ts',
    'src/components/canvas/emptyPlaceholders.tsx',
  ],
  format: ['esm'],
  dts: true,
  splitting: true,
  sourcemap: false,
  clean: true,
  minify: true,
});
