id: productCategory
displayName: Product Category
path: /single
custom:
  allowedContentTypes:
    - productCategory
method: GET
purgeKey: 1e7eae47-8f5d-44b3-a9eb-41b7a5c15875
archetype: singleEntry
variables:
  entryId:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
