id: 88bfbe40-6e3c-480d-b6cd-7b3808e402a2
name: Shopping Assistant recommendations
order: 1400
path: /:locale/ai-assistant-configuration
type: composition
pathSegment: ai-assistant-configuration
data:
  queryStrings:
    - name: product-slugs
      value: >-
        peruvian-blend-coffee-134, house-blend-coffee-131,
        kosmic-coffee-barista-express-espresso-machine-115
      helpText: ''
compositionId: c7800fa4-a196-4560-b726-a4362918184e
projectMapId: 537d11ff-9ebe-4420-9682-36694477e2f9
