id: getLocalizationSettings
displayName: Get Localization Settings
ttl: 30
path: /api/locale
custom:
  proposedName: api/locale
method: GET
purgeKey: b6010bbf-9202-4055-bac1-5ecb1f525386
archetype: default
dataSourceId: nextApi
allowedOnComponents: []
