id: recipe
name: Recipe
created: '2025-01-29T11:28:56.30487+00:00'
updated: '2025-01-29T11:28:56.30487+00:00'
slugSettings:
  unique: local
  required: 'yes'
  regularExpression: ''
  regularExpressionMessage: ''
useTeamPermissions: true
fields:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig:
      required: true
    localizable: false
  - id: description
    name: Description
    type: text
    helpText: ''
    typeConfig:
      required: true
      multiline: true
      linesCount: 5
    localizable: false
  - id: image
    name: Image
    type: asset
    helpText: used in the list views
    typeConfig:
      max: 1
      required: true
    localizable: false
  - id: steps
    name: Steps
    type: $block
    helpText: ''
    typeConfig:
      min: 1
      allowedTypes:
        - recipeStep
  - id: categories
    name: Categories
    type: contentReference
    typeConfig:
      min: 1
      isMulti: true
      required: true
      allowedContentTypes:
        - recipeCategory
entryName: title
thumbnailField: image
description: ''
icon: list
type: contentType
permissions: []
previewConfigurations: []
